add_test([=[IRBuilderTest.SimpleReturn42]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.SimpleReturn42]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.SimpleReturn42]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IRBuilderTest.ReturnZero]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.ReturnZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.ReturnZero]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IRBuilderTest.BinaryAdd]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.BinaryAdd]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.BinaryAdd]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IRBuilderTest.Compare]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.Compare]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.Compare]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IRBuilderTest.UnaryMinus]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.UnaryMinus]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.UnaryMinus]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IRBuilderTest.UnaryNot]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.UnaryNot]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.UnaryNot]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IRBuilderTest.PrinterStability]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.PrinterStability]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.PrinterStability]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IRBuilderTest.LogicalAnd]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.LogicalAnd]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.LogicalAnd]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IRBuilderTest.LogicalOr]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.LogicalOr]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.LogicalOr]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IRBuilderTest.ShortCircuitAndDivZero]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.ShortCircuitAndDivZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.ShortCircuitAndDivZero]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IRBuilderTest.ShortCircuitOrDivZero]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.ShortCircuitOrDivZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.ShortCircuitOrDivZero]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IRBuilderTest.VariableDeclaration]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.VariableDeclaration]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.VariableDeclaration]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IRBuilderTest.Assignment]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.Assignment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.Assignment]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IRBuilderTest.IfElse]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.IfElse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.IfElse]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IRBuilderTest.WhileLoop]=]  E:/TOYC/artifacts/independent_audit/build_r1/ir_builder_test.exe [==[--gtest_filter=IRBuilderTest.WhileLoop]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IRBuilderTest.WhileLoop]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  ir_builder_test_TESTS IRBuilderTest.SimpleReturn42 IRBuilderTest.ReturnZero IRBuilderTest.BinaryAdd IRBuilderTest.Compare IRBuilderTest.UnaryMinus IRBuilderTest.UnaryNot IRBuilderTest.PrinterStability IRBuilderTest.LogicalAnd IRBuilderTest.LogicalOr IRBuilderTest.ShortCircuitAndDivZero IRBuilderTest.ShortCircuitOrDivZero IRBuilderTest.VariableDeclaration IRBuilderTest.Assignment IRBuilderTest.IfElse IRBuilderTest.WhileLoop)
