if(EXISTS "E:/TOYC/artifacts/independent_audit/build_r1/ir_model_test[1]_tests.cmake")
  include("E:/TOYC/artifacts/independent_audit/build_r1/ir_model_test[1]_tests.cmake")
else()
  add_test(ir_model_test_NOT_BUILT ir_model_test_NOT_BUILT)
endif()
