add_test([=[LexerTest.SimpleInteger]=]  E:/TOYC/artifacts/independent_audit/build_r1/lexer_test.exe [==[--gtest_filter=LexerTest.SimpleInteger]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.SimpleInteger]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.KeywordInt]=]  E:/TOYC/artifacts/independent_audit/build_r1/lexer_test.exe [==[--gtest_filter=LexerTest.KeywordInt]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.KeywordInt]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.KeywordReturn]=]  E:/TOYC/artifacts/independent_audit/build_r1/lexer_test.exe [==[--gtest_filter=LexerTest.KeywordReturn]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.KeywordReturn]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.FullProgram]=]  E:/TOYC/artifacts/independent_audit/build_r1/lexer_test.exe [==[--gtest_filter=LexerTest.FullProgram]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.FullProgram]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.Operators]=]  E:/TOYC/artifacts/independent_audit/build_r1/lexer_test.exe [==[--gtest_filter=LexerTest.Operators]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.Operators]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.LineComment]=]  E:/TOYC/artifacts/independent_audit/build_r1/lexer_test.exe [==[--gtest_filter=LexerTest.LineComment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.LineComment]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.BlockComment]=]  E:/TOYC/artifacts/independent_audit/build_r1/lexer_test.exe [==[--gtest_filter=LexerTest.BlockComment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.BlockComment]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.MultiLineBlockComment]=]  E:/TOYC/artifacts/independent_audit/build_r1/lexer_test.exe [==[--gtest_filter=LexerTest.MultiLineBlockComment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.MultiLineBlockComment]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.ParenthesesAndBraces]=]  E:/TOYC/artifacts/independent_audit/build_r1/lexer_test.exe [==[--gtest_filter=LexerTest.ParenthesesAndBraces]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.ParenthesesAndBraces]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.ErrorUnexpectedChar]=]  E:/TOYC/artifacts/independent_audit/build_r1/lexer_test.exe [==[--gtest_filter=LexerTest.ErrorUnexpectedChar]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.ErrorUnexpectedChar]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.SingleEqNowValid]=]  E:/TOYC/artifacts/independent_audit/build_r1/lexer_test.exe [==[--gtest_filter=LexerTest.SingleEqNowValid]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.SingleEqNowValid]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_r1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  lexer_test_TESTS LexerTest.SimpleInteger LexerTest.KeywordInt LexerTest.KeywordReturn LexerTest.FullProgram LexerTest.Operators LexerTest.LineComment LexerTest.BlockComment LexerTest.MultiLineBlockComment LexerTest.ParenthesesAndBraces LexerTest.ErrorUnexpectedChar LexerTest.SingleEqNowValid)
