add_test([=[ParserTest.SimpleReturn42]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.SimpleReturn42]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.SimpleReturn42]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.ReturnZero]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.ReturnZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.ReturnZero]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.UnaryMinus]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.UnaryMinus]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.UnaryMinus]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.UnaryNot]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.UnaryNot]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.UnaryNot]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.BinaryAdd]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.BinaryAdd]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.BinaryAdd]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.PrecedenceAddMul]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.PrecedenceAddMul]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.PrecedenceAddMul]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.ParenthesesOverridePrecedence]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.ParenthesesOverridePrecedence]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.ParenthesesOverridePrecedence]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.Comparison]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.Comparison]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.Comparison]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.Equality]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.Equality]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.Equality]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.LogicalAndOr]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.LogicalAndOr]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.LogicalAndOr]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.VarDecl]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.VarDecl]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.VarDecl]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.Assignment]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.Assignment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.Assignment]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.IfElse]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.IfElse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.IfElse]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.DanglingElse]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.DanglingElse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.DanglingElse]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.ErrorMissingSemicolon]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.ErrorMissingSemicolon]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.ErrorMissingSemicolon]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.ErrorMissingParen]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.ErrorMissingParen]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.ErrorMissingParen]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.ErrorExtraTokens]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.ErrorExtraTokens]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.ErrorExtraTokens]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.ErrorNonMain]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.ErrorNonMain]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.ErrorNonMain]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.SemanticMissingReturn]=]  E:/TOYC/artifacts/independent_audit/build_cpp/parser_test.exe [==[--gtest_filter=ParserTest.SemanticMissingReturn]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.SemanticMissingReturn]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  parser_test_TESTS ParserTest.SimpleReturn42 ParserTest.ReturnZero ParserTest.UnaryMinus ParserTest.UnaryNot ParserTest.BinaryAdd ParserTest.PrecedenceAddMul ParserTest.ParenthesesOverridePrecedence ParserTest.Comparison ParserTest.Equality ParserTest.LogicalAndOr ParserTest.VarDecl ParserTest.Assignment ParserTest.IfElse ParserTest.DanglingElse ParserTest.ErrorMissingSemicolon ParserTest.ErrorMissingParen ParserTest.ErrorExtraTokens ParserTest.ErrorNonMain ParserTest.SemanticMissingReturn)
