add_test([=[RiscvEmitterTest.SimpleReturn42]=]  E:/TOYC/artifacts/independent_audit/build_cpp/riscv_emitter_test.exe [==[--gtest_filter=RiscvEmitterTest.SimpleReturn42]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RiscvEmitterTest.SimpleReturn42]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RiscvEmitterTest.ReturnZero]=]  E:/TOYC/artifacts/independent_audit/build_cpp/riscv_emitter_test.exe [==[--gtest_filter=RiscvEmitterTest.ReturnZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RiscvEmitterTest.ReturnZero]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RiscvEmitterTest.BinaryAdd]=]  E:/TOYC/artifacts/independent_audit/build_cpp/riscv_emitter_test.exe [==[--gtest_filter=RiscvEmitterTest.BinaryAdd]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RiscvEmitterTest.BinaryAdd]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RiscvEmitterTest.CompareLt]=]  E:/TOYC/artifacts/independent_audit/build_cpp/riscv_emitter_test.exe [==[--gtest_filter=RiscvEmitterTest.CompareLt]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RiscvEmitterTest.CompareLt]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RiscvEmitterTest.UnaryNeg]=]  E:/TOYC/artifacts/independent_audit/build_cpp/riscv_emitter_test.exe [==[--gtest_filter=RiscvEmitterTest.UnaryNeg]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RiscvEmitterTest.UnaryNeg]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RiscvEmitterTest.UnaryNot]=]  E:/TOYC/artifacts/independent_audit/build_cpp/riscv_emitter_test.exe [==[--gtest_filter=RiscvEmitterTest.UnaryNot]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RiscvEmitterTest.UnaryNot]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RiscvEmitterTest.HasTextSection]=]  E:/TOYC/artifacts/independent_audit/build_cpp/riscv_emitter_test.exe [==[--gtest_filter=RiscvEmitterTest.HasTextSection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RiscvEmitterTest.HasTextSection]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RiscvEmitterTest.ReturnUsesA0]=]  E:/TOYC/artifacts/independent_audit/build_cpp/riscv_emitter_test.exe [==[--gtest_filter=RiscvEmitterTest.ReturnUsesA0]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RiscvEmitterTest.ReturnUsesA0]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RiscvEmitterTest.ShortCircuitAnd]=]  E:/TOYC/artifacts/independent_audit/build_cpp/riscv_emitter_test.exe [==[--gtest_filter=RiscvEmitterTest.ShortCircuitAnd]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RiscvEmitterTest.ShortCircuitAnd]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RiscvEmitterTest.ShortCircuitOr]=]  E:/TOYC/artifacts/independent_audit/build_cpp/riscv_emitter_test.exe [==[--gtest_filter=RiscvEmitterTest.ShortCircuitOr]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RiscvEmitterTest.ShortCircuitOr]=]  PROPERTIES WORKING_DIRECTORY E:/TOYC/artifacts/independent_audit/build_cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  riscv_emitter_test_TESTS RiscvEmitterTest.SimpleReturn42 RiscvEmitterTest.ReturnZero RiscvEmitterTest.BinaryAdd RiscvEmitterTest.CompareLt RiscvEmitterTest.UnaryNeg RiscvEmitterTest.UnaryNot RiscvEmitterTest.HasTextSection RiscvEmitterTest.ReturnUsesA0 RiscvEmitterTest.ShortCircuitAnd RiscvEmitterTest.ShortCircuitOr)
